/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./App.tsx', './src/**/*.{js,jsx,ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        'inverse-primary': '#526600',
        tertiary: '#ffffff',
        'on-error-container': '#ffdad6',
        'on-tertiary-fixed': '#1a1c1c',
        'on-secondary-fixed-variant': '#004f54',
        'surface-tint': '#aed500',
        'on-primary': '#293500',
        'on-tertiary-container': '#636565',
        surface: '#131313',
        'inverse-surface': '#e5e2e1',
        'on-background': '#e5e2e1',
        'on-secondary-fixed': '#002022',
        'surface-container-high': '#2a2a2a',
        'on-surface': '#e5e2e1',
        'primary-fixed': '#c7f300',
        background: '#131313',
        'on-tertiary': '#2f3131',
        primary: '#ffffff',
        'secondary-fixed': '#7df4ff',
        secondary: '#d3fbff',
        'primary-container': '#c7f300',
        'surface-container-lowest': '#0e0e0e',
        'secondary-container': '#00eefc',
        'primary-fixed-dim': '#aed500',
        'error-container': '#93000a',
        'on-primary-fixed': '#171e00',
        'surface-container-low': '#1c1b1b',
        'inverse-on-surface': '#313030',
        error: '#ffb4ab',
        'surface-container-highest': '#353534',
        'on-surface-variant': '#c5c9ac',
        'outline-variant': '#444933',
        'surface-dim': '#131313',
        'secondary-fixed-dim': '#00dbe9',
        'surface-bright': '#3a3939',
        'surface-variant': '#353534',
        'on-primary-container': '#576c00',
        'surface-container': '#201f1f',
        'on-error': '#690005',
        'on-secondary-container': '#00686f',
        'tertiary-fixed-dim': '#c6c6c7',
        'on-secondary': '#00363a',
        'tertiary-container': '#e2e2e2',
        'tertiary-fixed': '#e2e2e2',
        'on-tertiary-fixed-variant': '#454747',
        'on-primary-fixed-variant': '#3d4d00',
        outline: '#8e9378',
      },
      borderRadius: {
        DEFAULT: '4px',
        sm: '2px',
        md: '6px',
        lg: '8px',
        xl: '12px',
        full: '9999px',
      },
      spacing: {
        xs: '4px',
        base: '8px',
        sm: '12px',
        gutter: '16px',
        md: '24px',
        lg: '40px',
        xl: '64px',
        'margin-mobile': '20px',
      },
      fontFamily: {
        h1: ['Lexend_800ExtraBold'],
        h2: ['Lexend_700Bold'],
        h3: ['Lexend_700Bold'],
        'stat-display': ['Lexend_800ExtraBold'],
        'body-md': ['Inter_400Regular'],
        'body-lg': ['Inter_400Regular'],
        'label-caps': ['Inter_700Bold'],
      },
    },
  },
  plugins: [],
};
